version: '3.7'

services:
  minio1:
    image: minio/minio
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: 123
      MINIO_SECRET_KEY: 12345678
    command: server /data
